name: Test Artifact
on: push

jobs:
  test-artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: echo 123 > text.txt
      - uses: actions/upload-artifact@v4
        with:
          name: myfirstartifact
          path: ./text.txt
  download-artifact:
    runs-on: ubuntu-latest
    needs: test-artifacts
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: myfirstartifact
          path: ./ici
      - run: |
          ls
          ls ./ici
          cat ./ici/text.txt
