name: backup database

on:
  schedule:
    - cron: "58 10 * * *"
    - cron: "58 11 * * *"
    - cron: "58 12 * * *"
  # on ajoute workflow_dispatch pour pouvoir lancer le workflow manuellement
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: backup database
        run: echo "Backup database"
