name: workgin directory et shell
on: push
defaults:
  run:
    shell: bash
    working-directory: ./frontend

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
      # si on le lance comme ça cela va provoquer une erreur
      # car notre package.json est dans le dossier /frontend
      - name: install dependencies
        run: npm install
