on:
  push:
    branches: [ main ]

jobs:
  mission-mars:
    runs-on: ubuntu-latest
    steps:
      - name: Mission Mars
        run: |
          echo "=== Mission Mars ==="
          echo "Équipements :"
          echo "- Rover"
          echo "- Combinaison spatiale"
          echo "Durée du voyage : 7 mois"
          echo "Activité principale : Analyse des roches"
          echo "Type de destination : planete"
          echo "=== Fin de la mission ==="

  mission-lune:
    runs-on: ubuntu-latest
    steps:
      - name: Mission Lune
        run: |
          echo "=== Mission Lune ==="
          echo "Équipements :"
          echo "- Module lunaire"
          echo "- Combinaison spatiale"
          echo "Durée du voyage : 3 jours"
          echo "Activité principale : Collecte d'échantillons"
          echo "Type de destination : satellite"
          echo "=== Fin de la mission ==="

  mission-venus:
    runs-on: ubuntu-latest
    steps:
      - name: Mission Vénus
        run: |
          echo "=== Mission Vénus ==="
          echo "Équipements :"
          echo "- Sonde atmosphérique"
          echo "- Instruments scientifiques"
          echo "Durée du voyage : 5 mois"
          echo "Activité principale : Analyse atmosphérique"
          echo "Type de destination : planete"
          echo "=== Fin de la mission ==="