name: issue_created
on:
  issues:
    types:
      - opened

jobs:
  alert:
    runs-on: ubuntu-latest

    steps:
      - name: title issue
        run: |
          echo "Le titre de l'issue est: ${{ github.event.issue.title }}"
      - name: description issue
        run: |
          echo "La description de l'issue est: ${{ github.event.issue.body }}"
