name: workgin directory et shell
on: push
defaults:
  run:
    working-directory: ./frontend
    shell: bash

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      # AJOUT 1
      - name: Lookup npm cache
        id: npm-cache-lookup
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          lookup-only: true
      # AJOUT 2
      - name: Display cache lookup status
        run: |
          if [[ "${{ steps.npm-cache-lookup.outputs.cache-hit }}" == "true" ]]; then
            echo "✅ Cache existe mais n’a pas été restauré."
          else
            echo "❌ Aucun cache trouvé."
          fi
      - name: Cache dependencies
        uses: actions/cache@v4
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          # Par convention on peut ajouter node- avant le hash. Ce n’est pas obligatoire mais c’est plus clair pour différencier les caches si on en utilise plusieurs dans notre workflow (un pour python, un pour build, …).
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
          # AJOUT 3
          fail-on-cache-miss: true
      - name: display cache statut
        run: |
          if [ "${{ steps.npm-cache.outputs.cache-hit }}" == "true" ]; then
            echo "✅ cache récupéré"
          else
            echo "❌ pas de cache récupéré"
          fi
      - name: install dependencies
        run: npm ci
