name: workflow commands
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::notice::Un message d'info"
          echo "::warning::Un warning"
          echo "::error::Une erreur"
