name: Container Docker

on: push

jobs:
  avec-container:
    runs-on: ubuntu-latest
    container:
      image: node:22
      volumes:
        - my_volume:/app/temp
    steps:
      - run: |
          echo "Hello from Volume" > /app/temp/hello.txt

      - run: |
          cat /app/temp/hello.txt
