name: Container Docker

on: push

jobs:
  avec-container:
    runs-on: ubuntu-latest
    container:
      image: node:22
      env:
        NODE_ENV: "production"
    steps:
      - run: |
          echo "NODE_ENV: $NODE_ENV"
