name: Container Docker

on: push

jobs:
  classique:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job classique"
          echo "pwd: $(pwd)"
          echo "ls -la: $(ls -la)"
          echo "node -v: $(node -v)"

  avec-container:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - run: |
          echo "Job avec container"
          echo "pwd: $(pwd)"
          echo "ls -la: $(ls -la)"
          echo "node -v: $(node -v)"
