name: backup database

on:
  schedule:
    - cron: "40 9 * * *"
    - cron: "40 10 * * *"
    - cron: "40 11 * * *"
  # on ajoute workflow_dispatch pour pouvoir lancer le workflow manuellement
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: backup database
        run: echo "Backup database"
