name: Exploration Spatiale - Version Matrice

on:
  push:
    branches: [main]

jobs:
  exploration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mission:
          - nom: Mars
            duree: "7 mois"
            equipements: ["Rover", "Combinaison spatiale"]
            activite: "Analyse des roches"
            type: "planete"
          - nom: Lune
            duree: "3 jours"
            equipements: ["Module lunaire", "Combinaison spatiale"]
            activite: "Collecte d'échantillons"
            type: "satellite"
          - nom: Vénus
            duree: "5 mois"
            equipements: ["Sonde atmosphérique", "Instruments scientifiques"]
            activite: "Analyse atmosphérique"
            type: "planete"

    steps:
      - name: Mission ${{ matrix.mission.nom }}
        run: |
          echo "=== Mission ${{ matrix.mission.nom }} ==="
          echo "Équipements :"
          echo "- ${{ matrix.mission.equipements[0] }}"
          echo "- ${{ matrix.mission.equipements[1] }}"
          echo "Durée du voyage : ${{ matrix.mission.duree }}"
          echo "Activité principale : ${{ matrix.mission.activite }}"
          echo "Type de destination : ${{ matrix.mission.type }}"
          echo "=== Fin de la mission ==="

  demandes_president:
    needs: exploration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nom: [Mars, Lune, Vénus]
        include:
          - nom: Mars
            equipement_special: "Space Burger"
            commentaire: "Pour maintenir le moral de l'équipage"
          - nom: Lune
            equipement_special: "Télescope pour observer les aliens"
            commentaire: "Parce que les aliens existent, c'est sûr !"

    steps:
      - name: Demandes spéciales pour ${{ matrix.mission.nom }}
        run: |
          echo "=== Demandes spéciales du Président pour ${{ matrix.mission.nom }} ==="
          echo "Équipement spécial : ${{ matrix.equipement_special || 'Pas besoin' }}"
          echo "Commentaire : ${{ matrix.commentaire || 'Aucun commentaire' }}"
          echo "=== Fin des demandes spéciales ==="
