name: github-event

on:
  push:

jobs:
  github-env:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          # github fournit un outil jq pour afficher les json
          echo $EVENT_CONTEXT | jq
