name: workflow

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: tâche de job1
        run: echo "Exécution de job1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: tâche de job2
        run: echo "Exécution de job2"
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: tâche de job3
        run: echo "Exécution de job3 après job1 et 2"
