name: Mon premier workflow
on:
  push:
    # on peut faire toutes les branches et ignorer main
    # suppression branches
    # test push sur main
    # test push sur develop
    # branches:
    #   - feature
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo JOB DONE
