name: Mon premier workflow
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
      - run: echo STEP 1
        # ajout
      - if: always()
        run: echo STEP 2
        # le contenu de if est considéré comme une expression
        # pas besoin de mettre $ et double accolade
      - run: echo STEP 3
      - if: failure()
        run: echo STEP 4
      - if: success()
        run: echo STEP 5
      - run: echo STEP 6
