name: Mon premier workflow
on: push

env:
  VAR_FROM_WORKFLOW: from workflow

jobs:
  test-variables:
    env:
      NAME: Nom se ma step
    runs-on: ubuntu-latest
    steps:
      - name: ${{ env.NAME }}
        run: |
          echo "Var depuis workflow: $VAR_FROM_WORKFLOW" 
          echo "Var depuis workflow: ${{ env.VAR_FROM_WORKFLOW }}"
          echo "github ref: $GITHUB_REF"
          echo "github ref: ${{ github.ref }}"
          echo "github event: $GITHUB_EVENT_NAME"
          echo "Variable de projet: ${{ vars.VAR_PROJECT }}"
          echo "Secret de projet:  ${{ secrets.SECRET_PROJECT }}"
