name: Mon premiere workflow
on: push
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Voir ce que contient notre runner
        run:  pwd
      - run: echo "seconde step"
  
