name: Mon premier workflow
on: push

env:
  VAR_FROM_WORKFLOW: from workflow

jobs:
  test-variables:
    env:
      VAR_FROM_JOB: from job
    runs-on: ubuntu-latest
    steps:
      - name: les variables
        env:
          VAR_FROM_STEP: from step
          VAR_FROM_WORKFLOW: En fait je viens du step
        run: |
          echo "Var depuis workflow: $VAR_FROM_WORKFLOW"
          echo "Var depuis le job: $VAR_FROM_JOB"
          echo "Var depuis step: $VAR_FROM_STEP"
          echo "github ref: $GITHUB_REF"
          echo "github event: $GITHUB_EVENT_NAME"
          # modifications avec le contexte
          echo "Variable de projet: ${{ vars.VAR_PROJECT }}"
          echo "Secret de projet:  ${{ secrets.SECRET_PROJECT }}"
