name: Matrix workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [22, 24]
        include:
          - os: macos-latest
    steps:
      - run: |
          echo "Running on ${{ matrix.os }} with node ${{ matrix.node-version }}"
