name: Matrix workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [22, 24]
        exclude:
          - os: macos-latest
            node-version: 24
          - os: windows-latest
    steps:
      - run: |
          echo "Running on ${{ matrix.os }} with node ${{ matrix.node-version }}"
