name: Mon premier workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20, 22]
    steps:
      - run: echo "Running on ${{ matrix.os }} with node ${{ matrix.node-version }}"
