name: Mon premier workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # Ajout permissions pour pouvoir commit et push
    #! AVANT DE COMMIT:
    # Boucle infinie?
    # event sur le push > commit > push > event sur le push > commit > push > ...
    # Mais en fait non car après le push le même event n'est plus déclenché
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo 123 > test.txt
          # on doit configurer le mail et name pour pouvoir commit et push
          # l'action cehckout ne configure pas le mail et name
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add test.txt
          git commit -m "Add test.txt"
          git push origin main
