name: production workflow
on:
  push:
    branches: main

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://mon-application.fr
    steps:
      - run: |
          echo Deploy to production
          echo "secrets fron staging environnement" ${{ secrets.DATABASE_PASSWORD }}
          echo "DATABASE_URL from staging environnement" ${{ env.DATABASE_URL }}
