name: production workflow
on:
  push:
    branches: main

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://mon-application.fr
    steps:
      - run: |
          echo Deploy to production
