name: Services
on: push

jobs:
  test-services:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: installation redis-cli
        # -y pour accepter les prompts
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-tools

      - run: |

          # Pas besoin de préciser le port car le 6379 est le port par default
          echo 'test connexion' $(redis-cli -h localhost -p 6379 PING)
          # Ajout de données dans redis
          # -h pour host
          redis-cli -h localhost SET user:1 '{"id":1,"name":"Henri"}'
          redis-cli -h localhost SET user:2 '{"id":2,"name":"Alice"}'
          # Récupération des données
          echo "user 1: $(redis-cli -h localhost GET user:1)"
          echo "user 2: $(redis-cli -h localhost GET user:2)"
