name: workgin directory et shell
on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
      - run: |
          pwd
        shell: sh
      - run: |
          pwd
        shell: pwsh
