name: workgin directory et shell
on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
          echo $SHELL
      - run: |
          pwd
          echo $0
        shell: sh
      # powershell
      - run: |
          Get-Location
          Write-Host "PowerShell Version: $($PSVersionTable.PSVersion)"
          Write-Host "Current Shell: $($PSVersionTable.PSEdition)"
        shell: pwsh
