name: staging workflow
on:
  push:
    branches: staging

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://mon-application-staging.fr
    steps:
      - run: |
          echo Deploy to staging environnement
          echo "secret password" ${{ secrets.DATABASE_PASSWORD }}
          # Rappel pour créer une variable d'environnement depuis l'UI de GITHUB on utilise vars
          echo "DATABASE_URL" ${{ vars.DATABASE_URL }}
